Aplicação-RotasCommunity/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/help'
  get 'static_pages/quemsomos'

  get 'sessions/new'

  get 'static_pages/home'
  get 'static_pages/seguir'
  get 'users/todos'

root 'static_pages#home'
 

  resources :routes
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users 

end

Aplicação-RotasCommunity/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @users = User.all
      
  end



  def help
  end

  def seguir
    @route = Route.find(params[:route])
    flash[:success] = "Rota selecionada"
    redirect_to(root_url)
  end	
end

Aplicação-RotasCommunity/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Aplicação-RotasCommunity/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

Aplicação-RotasCommunity/app/views/static_pages/home.html.erb
<% if !logged_in? %>

<!DOCTYPE html>
<br>
    <html lang="en">

    <head>

    <meta charset="utf-8">

    <title>Rotas Community</title>

    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">

    <link rel="stylesheet" type="text/css" href="css/custom.css">

    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>

    <script type="text/javascript" src="js/bootstrap.min.js"></script>

    </head>

    <body>

        
            <!-- Brand and toggle get grouped for better mobile display -->

            

       <div align="center">

            <div class="container-fluid">


                     
                <img alt="teste" src="http://www.gruponasa.com.br/arquivos/1-6-download-822718_g.jpg" width="1000" height="450" class="img-rounded" />
                <link href="/assets/custom.css.scss?body=1" media="screen" rel="stylesheet" />
                <br>
                <div align="center"> 
                <br>

<div class="btn-group" role="group" aria-label="...">
               <%= link_to t('.Cadastre-se no sistema', :default => t("helpers.links.Cadastre-se no sistema")),new_user_path, :class => 'btn btn-default btn' %>

                </div>
                </div>
               
                
</div>
            </div>

        

        <div class="container-fluid">

            <div class="row">

                <div class="col-xs-4">

                    <h2>Quem somos</h2>

                    <p>Um pouco a respeito da organização envolvida no desenvolvimento do sistema Rotas Community</p>

                    <div align="center"> 
                <br>

                <div class="btn-group" role="group" aria-label="...">
               
                    <%= link_to t('.Quem Somos', :default => t("helpers.links.Quem somos")),static_pages_quemsomos_path, :class => 'btn btn-default btn' %>
                    
                </div>
                </div>

                </div>

                <div class="col-xs-4">

                    <h2>Oportunidade de Rotas</h2>

                    <p>Aqui você pode verificar todas as rotas disponiveis para você trabalhar!</p>

                <div align="center"> 
                <br>

                <div class="btn-group" role="group" aria-label="...">

                     <%= link_to t('.Rotas disponiveis', :default => t("helpers.links.Rotas disponiveis")),routes_path, :class => 'btn btn-default btn' %>
                    
                </div>
                </div>
               
                    

                </div>

                <div class="col-xs-4">

                    <h2>Pesquisa por Frete</h2>

                    <p>Consulte aqui sua carta-frete.</p>

                    <div align="center"> 
             <%= form_tag(routes_path, :method => "get", id: "search-form") do %>
                 <%= search_field_tag :search, params[:search], placeholder: 'Carta-frete',
      size: 40, class: 'form-control' %> 
                        <%= submit_tag "Pesquisar", name: nil, class: 'btn btn-default' %>
                        <% end %>   
                </div>
</div>

            </div>

            <hr>

            <div class="row">

                <div class="col-xs-12">

                    

                </div>

            </div>

        </div>

    </body>

    </html>

<% end %>


<% if logged_in? %>
<br>
<% if current_user.admin? %>

<br>

  

<%= render template: 'users/index' %>

<% elsif %>


   <!DOCTYPE html>
<br>
    <html lang="en">

    <head>

    <meta charset="utf-8">

    <title>Rotas Community</title>

    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">

    <link rel="stylesheet" type="text/css" href="css/custom.css">

    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>

    <script type="text/javascript" src="js/bootstrap.min.js"></script>

    </head>

    <body>

        
            <!-- Brand and toggle get grouped for better mobile display -->

            

       <div align="center">

            <div class="container-fluid">


                     
                <img alt="teste" src="http://www.gruponasa.com.br/arquivos/1-6-download-822718_g.jpg" width="1000" height="450" />
                <link href="/assets/custom.css.scss?body=1" media="screen" rel="stylesheet" />
                <br>
                <div align="center"> 
                <br>

<div class="btn-group" role="group" aria-label="...">
               
                     <%= link_to t('.Cadastre-se no sistema', :default => t("helpers.links.Cadastre-se no sistema")),new_user_path, :class => 'btn btn-default btn' %>  
  
                </div>
                </div>
               
                
</div>
            </div>

        

        <div class="container-fluid">

            <div class="row">

                       <div class="col-xs-4">

                    <h2>Quem somos</h2>

                    <p>Um pouco a respeito da organização envolvida no desenvolvimento do sistema Rotas Community</p>

                    <div align="center"> 
                <br>

                <div class="btn-group" role="group" aria-label="...">
                <%= link_to t('.Quem Somos', :default => t("helpers.links.Quem somos")),static_pages_quemsomos_path, :class => 'btn btn-default btn' %>
                    
                </div>
                </div>

                </div>

                <div class="col-xs-4">

                    <h2>Oportunidade de Rotas</h2>

                    <p>Aqui você pode verificar todas as rotas disponiveis para você trabalhar!</p>

                <div align="center"> 
                <br>

                <div class="btn-group" role="group" aria-label="...">
               
                     <%= link_to t('.Rotas disponiveis', :default => t("helpers.links.Rotas disponiveis")),routes_path, :class => 'btn btn-default btn' %>
                </div>
                </div>
               
                    

                </div>

                <div class="col-xs-4">

                      <h2>Pesquisa por Frete</h2>

                    <p>Consulte aqui sua carta-frete.</p>

                    <div align="center"> 
                <br>

            <%= form_tag(routes_path, :method => "get", id: "search-form") do %>
                    <%= search_field_tag :search, params[:search], placeholder: 'Search for something',
      size: 40, class: 'form-control' %> 
                        <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
            <% end %>               
                    
                    </div>
                </div>
                </div>

            </div>

            <hr>

            <div class="row">

                <div class="col-xs-12">

                    

                </div>

            </div>

        </div>

    </body>

    </html>


<% end %>

<% end %>

Aplicação-RotasCommunity/app/views/static_pages/quemsomos.html.erb
<!DOCTYPE html>
<br>
    <html lang="en">

    <head>

    <meta charset="utf-8">

    <title>Rotas Community</title>

    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">

    <link rel="stylesheet" type="text/css" href="css/custom.css">

    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>

    <script type="text/javascript" src="js/bootstrap.min.js"></script>

    </head>

    <body>

        
            <!-- Brand and toggle get grouped for better mobile display -->

            

       <div align="center">

            <div class="container-fluid">


                
                <div align="center">

            <div class="container-fluid">


                     
                <img alt="teste" src="                https://uploaddeimagens.com.br/images/000/436/076/original/Sem_t%C3%ADtulo.png?1422297023
" class="img-rounded" />
                <link href="/assets/custom.css.scss?body=1" media="screen" rel="stylesheet" />
                <br>
                <div align="center"> 
                <br>
                                
               <p align=”Justify”> A Rota transportes e Logística Ltda é uma empresa relativamente nova no mercado, cuja fundação foi em janeiro de 2007. Apesar  nova já tínhamos alguma experiência, pois os sócios administravam uma outra empresa do ramo de corretagem de grãos, cuja, uma das atividades  era o agenciamento de caminhões para o transporte dos grãos entre o produtor e o comprador. Essa atividade foi nos proporcionando um “expertise“ que nos permitiu investir em caminhões para o transporte desses grãos.</p>

<p align=”Justify”>No princípio tivemos as dificuldades inerentes aos massivos investimentos que são normais em uma empresa de transporte, devido ao alto valor dos equipamentos e também a falta de experiência no gerenciamento da frota, mas no decorrer dos anos fomos aprimorando os controles internos e ganhando experiência operacional que tem nos possibilitado crescer com segurança e permanentemente. Iniciamos com uma frota de 06 veículos e atualmente nossa frota é de 20 veículos, todos rastreados por satélite e dezenas de agregados. Nosso diferencial está nos princípios de qualidade na prestação de serviços, rigor nos controles internos para a manutenção dos custos a níveis baixos, gestão financeira rígida para depender o mínimo de recursos de terceiros, oficina própria para manutenção preventiva constante e administração operacional permanente com negociação de cargas de ida e de retorno para que a frota produza ao máximo e com o mínimo de desperdício.</p>

<p align=”Justify”>Acreditamos em uma expansão considerável no faturamento ano após ano, devido ao grau de especialização que vivemos e também a melhor condição econôm ica da empresa à medida que o retorno do investimento se realiza.</p>     <!-- COLOCAR AQUI O QUEM SOMOS DA EMPRESA -->
                <br>
                <br>


    </body>

    </html>

Aplicação-RotasCommunity/app/views/static_pages/seguir.html.erb
<% if current_user %>
  <% @route.update_column(:user_id, current_user.id) %>
  <% @route.save %>

<%= render template: 'users/show' %>

<% end %>  