Aplicação-RotasCommunity/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/help'
  get 'static_pages/quemsomos'

  get 'sessions/new'

  get 'static_pages/home'
  get 'static_pages/seguir'
  get 'users/todos'

root 'static_pages#home'
 

  resources :routes
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users 

end

Aplicação-RotasCommunity/app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :user       #FAZ PARTE DO USUÁRIO 
      validates_presence_of :origem, :destino, :tipo, :data, :tipo
    

def self.search(query) #CONSULTANDO A TABELA ROTAS - NO ATRIBUTO FRETE
  		where("frete like ?", "%#{query}%") 
	end

WillPaginate.per_page = 10

end

Aplicação-RotasCommunity/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  
    
    def index

         if params[:search]
          @routes = Route.search(params[:search]).paginate(page: params[:page]) 
          else
          @routes = Route.all.paginate(page: params[:page])  
        end

     
       
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
    
  end

  def search
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
     @route = Route.find(params[:id])
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
    flash[:success] = "Rota criada!" 
    format.html { redirect_to @route}
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json


  def update
    
    respond_to do |format|
      if @route.update(route_params)
        
              flash[:success] = "Rota atualizada!" 

          format.html { redirect_to @route }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /routes/1
  # DELETE /routes/1.json3
  def destroy
    @route.destroy
    respond_to do |format|
            flash[:success] = "Rota deletada!" 

      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:origem, :destino, :data, :tipo, :obs, :pagamento, :frete)
    end
end

Aplicação-RotasCommunity/app/helpers/routes_helper.rb
module RoutesHelper
end

Aplicação-RotasCommunity/app/views/routes/_form.html.erb
<%= form_for @route, :html => { :class => "form-horizontal route" } do |f| %>

    <% if @route.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @route.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <div class="control-group">
    <%= f.label :Origem, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :origem, :class => 'form-control' %>
    </div>
    <%= error_span(@route[:origem]) %>
  </div>
  <div class="control-group">
    <%= f.label :destino, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :destino, :class => 'form-control' %>
    </div>
    <%= error_span(@route[:destino]) %>
  </div>
  <div class="control-group">
    <%= f.label :data, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :data, :class => 'form-control' %>
    </div>
    <%= error_span(@route[:data]) %>
  </div>
  <div class="control-group">
    <%= f.label :Tipo_caminhão, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tipo, :class => 'form-control' %>
    </div>
    <%= error_span(@route[:tipo]) %>
  </div>
  <div class="control-group">
    <%= f.label :Observações, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :obs, :class => 'form-control' %>
    </div>
    <%= error_span(@route[:obs]) %>
  </div>
  
  <div class="control-group">
    <%= f.label :Status_pagamento, :class => 'control-label' %>
    <div class="controls">
      <% if current_user.admin? %>

<%= select("route", "pagamento", ['Esperando','Pago'], {include_blank: "Situação do pagamento"}) %>
<% end %>
    </div>
    <%= error_span(@route[:pagamento]) %>
  </div>
  <div class="control-group">
    <%= f.label :Carta_frete, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :frete, :class => 'form-control' %>
    </div>
    <%= error_span(@route[:frete]) %>
  </div>



  <%= f.submit nil, :class => 'btn btn-primary' %></div>
</div>

  <%= link_to t('.cancelar', :default => t("helpers.links.cancelar")),
            routes_path, :class => 'btn btn-default' %>


<% end %>

Aplicação-RotasCommunity/app/views/routes/edit.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1><%=t 'Editar Rota', :default => [:'helpers.titles.editar', 'Editar Rota'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Aplicação-RotasCommunity/app/views/routes/index.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1>Todas as Rotas</h1>
</div>
<table class="table table-striped">
  <thead>
  
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:origem) %></th>
      <th><%= model_class.human_attribute_name(:destino) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:obs) %></th>
      <% if logged_in? %>
      <th><%= model_class.human_attribute_name(:pagamento) %></th>
      <th><%= model_class.human_attribute_name(:frete) %></th>
      <% end %>

       <% if logged_in? %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= link_to route.id, route_path(route) %></td>
        <td><%= route.origem %></td>
        <td><%= route.destino %></td>
        <td><%= route.data %></td>
        <td><%= route.tipo %></td>
        <td><%= route.obs %></td>
        <% if logged_in? %>
        <td><%= route.pagamento %></td>
        <td><%= route.frete %></td>
        <% end %>
        <td>
          <% if logged_in? && !current_user.admin?%>
        
         <%= link_to "Visualizar", route, class: "btn btn-primary btn-sm" %>


        <% end %>

        <% if logged_in? && current_user.admin?%>  
          <%= link_to t('.editar', :default => t("helpers.links.editar")),
                      edit_route_path(route), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      route_path(route),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>

                      <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>
<%= will_paginate %>
<br>
<br>
<% if logged_in? && current_user.admin?%>  
<%= link_to t('.Nova Rota', :default => t("helpers.links.Nova Rota")),
            new_route_path,
            :class => 'btn btn-primary' %>
            <% end %>

Aplicação-RotasCommunity/app/views/routes/new.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1><%=t '.Nova Rota', :default => [:'helpers.titles.Nova_Rota', 'Nova Rota'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

Aplicação-RotasCommunity/app/views/routes/show.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1> Rota </h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:origem) %>:</strong></dt>
  <dd><%= @route.origem %></dd>
  <dt><strong><%= model_class.human_attribute_name(:destino) %>:</strong></dt>
  <dd><%= @route.destino %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @route.data %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @route.tipo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:obs) %>:</strong></dt>
  <dd><%= @route.obs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @route.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pagamento) %>:</strong></dt>
  <dd><%= @route.pagamento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:frete) %>:</strong></dt>
  <dd><%= @route.frete %></dd>
</dl>

<%= link_to t('.Voltar', :default => t("helpers.links.Voltar")),
              routes_path, :class => 'btn btn-default'  %>

  <% if logged_in? && current_user.admin? %>
<%= link_to t('.editar', :default => t("helpers.links.editar")),
edit_route_path(@route), :class => 'btn btn-default' %>

<% end %>


        <% if logged_in? %>

                <%= link_to "Seguir esta Rota", static_pages_seguir_path(:route => @route.id), class: "btn btn-primary btn-sm" %>
<% end %>