Aplicação-RotasCommunity/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/help'
  get 'static_pages/quemsomos'

  get 'sessions/new'

  get 'static_pages/home'
  get 'static_pages/seguir'
  get 'users/todos'

root 'static_pages#home'
 

  resources :routes
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users 

end

Aplicação-RotasCommunity/app/models/user.rb
class User < ActiveRecord::Base
      attr_accessor :remember_token

    EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/


    has_many :routes

    validates_presence_of :name, :email, :cpf, :cnh, :telefone, :cidade, :endereco, :rg
    validates :cpf, length: { is: 11 }
      validates_uniqueness_of :cpf, :rg  
    validates_format_of :email, with: EMAIL_REGEXP
    
    has_secure_password
      # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
      end

    # Returns a random token.
    def User.new_token
    SecureRandom.urlsafe_base64
  end
    # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
     def authenticated?(remember_token)
         return false if remember_digest.nil?
         BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
    
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

Aplicação-RotasCommunity/app/controllers/users_controller.rb
  class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

    
 def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Por favor efetue o login."
        redirect_to login_url
      end
     end
     
  # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

     
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json

  def show
       @user = User.find(params[:id])
       @routes = @user.routes.paginate(page: params[:page])

  end

  def todos
      @user = User.all
     
    end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
          @user = User.find(params[:id])

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
                log_in @user

            flash[:success] = "Bem-vindo ao Rotas Community!"
            
          format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
          
        format.html { redirect_to @user }
           flash[:success] = "Dados atualizados"
      
              format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
        
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuário deletado"
      redirect_to users_url
          
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :cpf, :cidade, :telefone, :endereco, :rg, :cnh, :password, :password_confirmation)
    end
    WillPaginate.per_page = 10

end

Aplicação-RotasCommunity/app/helpers/users_helper.rb
module UsersHelper
end

Aplicação-RotasCommunity/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
  <div class="col-md-6 col-md-offset-3">

  <div class="control-group">
    <%= f.label :Nome_Completo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :CPF, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:cpf]) %>
  </div>
  <div class="control-group">
    <%= f.label :cidade, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cidade, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:cidade]) %>
  </div>
  <div class="control-group">
    <%= f.label :Telefone_Contato, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:telefone]) %>
  </div>
  <div class="control-group">
    <%= f.label :Endereço, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :endereco, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:endereco]) %>
  </div>
  <div class="control-group">
    <%= f.label :RG, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rg, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:rg]) %>
  </div>
  <div class="control-group">
    <%= f.label :CNH, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cnh, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:cnh]) %>
  </div>
  <div class="control-group">
    <%= f.label :Senha, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:password]) %>
  </div>
  <div class="control-group">
    <%= f.label :Confirmação_de_senha, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:password_confirmation]) %>
  </div>
 
  <%if logged_in? && current_user.admin? %>
  <div class="control-group">
    <%= f.label :admin, :class => 'control-label' %>

    <div class="controls">
      <%= f.text_field :admin, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:admin]) %>
  </div>
      <% end %>
      <%= f.submit nil, :class => 'btn btn-primary' %>

  </div>
  </div>  


  <%= link_to t('.cancelar', :default => t("helpers.links.cancelar")),
            users_path, :class => 'btn btn-default' %>

<% end %>

Aplicação-RotasCommunity/app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Editar Usuário</h1>
</div>
<%= render :partial => 'form' %>

Aplicação-RotasCommunity/app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Todos os usuários</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:cidade) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%= model_class.human_attribute_name(:rg) %></th>
      <th><%= model_class.human_attribute_name(:cnh) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.Opções', :default => t("helpers.opções") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.cpf %></td>
        <td><%= user.cidade %></td>
        <td><%= user.telefone %></td>
        <td><%= user.endereco %></td>
        <td><%= user.rg %></td>
        <td><%= user.cnh %></td>
        <td><%= user.password %></td>
        <td><%= user.admin %></td>
        <td><%=l user.created_at %></td>
        <td>

          <%= link_to t('.editar', :default => t("helpers.links.editar")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>

                      <%= link_to "Visualizar", user_path(user), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.Novo usuário', :default => t("helpers.links.Novo Usuário")),
            new_user_path,
            :class => 'btn btn-primary' %>

Aplicação-RotasCommunity/app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Novo Usuário </h1>
</div>
<%= render :partial => 'form' %>

Aplicação-RotasCommunity/app/views/users/show.html.erb
<br>
<% provide(:title, @user.name) %>
  <div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
<br>
        <div class="col-md-8">

<h3>Minhas rotas </h3>
     
      
<% if @user.routes.any? %>

      
<p>
    <ul class="routes">

          <% @user.routes.each do |route| %>
    
          <li>
                <% if current_user.admin? %>
            <p> ID: <%= link_to route.id, route_path(route) %></p>
            <% end %>
            <p><%= "Origem: #{route.origem} "%></p>
            <p><%= "Destino: #{route.destino} "%></p>
            <p><%= "Tipo: #{route.tipo}"%></p>
            <p><%= "Data: #{route.data} "%></p>
            <p><%= "Observações: #{route.obs} "%></p>
            <p><%= "Carta-frete: #{route.frete} "%></p>
            <p><%= "Situação do Pagamento: #{route.pagamento} "%></p>
            </li>
            
      
                  
                     

          
            
            

    

    <% end %>
</div>   
   </p>  


</div>
</ul>

<%= link_to t('.Editar Perfil', :default => t("helpers.links.Editar Perfil")),
              edit_user_path(@user), :class => 'btn btn-default' %>

  <% if logged_in? && current_user.admin?%>              
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<% end %>
<% end %>

Aplicação-RotasCommunity/app/views/users/todos.html.erb
<% provide(:title, 'Users') %>
<h1>Todas os usuários</h1>



<ul class="routes">
  <%  @user.each do |user| %>
    <li>
    <p><%= "Nome: #{user.name} "%></p>

    <%= link_to 'Editar', users_path %>
   
    </li>
  <% end %>
</ul>