Aplicação-RotasCommunity/config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/help'
  get 'static_pages/quemsomos'

  get 'sessions/new'

  get 'static_pages/home'
  get 'static_pages/seguir'
  get 'users/todos'

root 'static_pages#home'
 

  resources :routes
  
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users 

end

Aplicação-RotasCommunity/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://cin.ufpe.br/~lmc3">Lobo Alfa Dinamite</a>
    | <a href="http://www.google.com/">Google</a>
  </small>
  <nav>
    <ul>
      Versão Alpha 1.0
    </ul>
  </nav>
</footer>

Aplicação-RotasCommunity/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      
   <div class="navbar-header">
      <a class="navbar-brand", href="http://localhost:3000/">
<img alt="teste" src="https://uploaddeimagens.com.br/images/000/434/941/original/Logo_Rotas02.png?1422122825" width="205" height="53" class="img-rounded" />

                <link href="/assets/custom.css.scss?body=1" media="screen" rel="stylesheet" />

      </a>
    </div>

                
    <nav>
    
    <br>

      <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home", root_path %></li>

        
        <li><%= link_to "Rotas", routes_path %></li>
      
          <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Perfil <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Minhas Rotas", current_user %></li>
              <% if current_user.admin? %>
              <li><%= link_to "Adicionar Rota", new_route_path %></li>
              <% end%>
              <li><%= link_to "Editar perfil", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  
</header>

Aplicação-RotasCommunity/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

Aplicação-RotasCommunity/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-tubolinks-track' => true %>
    <%= csrf_meta_tags %>
              <%= render 'layouts/shim' %> <!--Para funcionar no explorer-->

  </head>
  <body>
          <%= render 'layouts/header' %>
    <br>
    <div class="container">
          <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %><!--Conteúdo da página-->
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>